# Generated by Django 3.2.9 on 2021-11-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211122_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essai',
        ),
    ]
